#!/usr/bin/env -S sh -c '$(which pypy3 || which python3) "$@"' -
# vi: ft=python

import argparse
import pkgutil
import sys
import os

import _tbl
from _tbl._base import _Base
from _tbl import _utils

def interpret_c_escapes(x: str):
    return x.encode('utf8').decode('unicode_escape').encode('utf8')

def resolve_auto_colour(x: str):
    return x == 'always' or (x == 'auto' and _utils.stdout_is_tty())

def make_parser(**kwargs):
    parser = argparse.ArgumentParser(allow_abbrev=False, **kwargs)
    group = parser.add_argument_group('common options')
    group.add_argument('-N', '--no-header', action='store_true')
    group.add_argument('--drop-header', action='store_true')
    group.add_argument('--trailer', choices=('never', 'always', 'auto'), default='auto', nargs='?')
    group.add_argument('--numbered-columns', choices=('never', 'always', 'auto'), default='auto', nargs='?')
    group.add_argument('-d', '--ifs', type=interpret_c_escapes)
    group.add_argument('--plain-ifs', action='store_true')
    group.add_argument('-D', '--ofs', type=interpret_c_escapes)
    group.add_argument('--irs', type=interpret_c_escapes, default=b'\n')
    group.add_argument('--ors', type=interpret_c_escapes)
    group.add_argument('--csv', dest='ifs', action='store_const', const=b',')
    group.add_argument('--tsv', dest='ifs', action='store_const', const=b'\t')
    group.add_argument('--ssv', dest='ifs', action='store_const', const=br'\s+')
    group.add_argument('--combine-trailing-columns', action='store_true')
    group.add_argument('-P', '--pretty', dest='ofs', action='store_const', const=_Base.PRETTY_OUTPUT)
    group.add_argument('--page', action='store_true')
    group.add_argument('--colour', '--color', choices=('never', 'always', 'auto'), default='auto', nargs='?')
    group.add_argument('--header-colour', type=_utils.utf8_type, default='\x1b[1;4m')
    group.add_argument('--header-bg-colour', type=_utils.utf8_type, default='\x1b[48;5;237m')
    group.add_argument('--rainbow-columns', choices=('never', 'always', 'auto'), default='auto', nargs='?')
    group.add_argument('-Q', '--no-quoting', action='store_true')
    return parser

def main():
    parent = make_parser(add_help=False, argument_default=argparse.SUPPRESS)
    parser = make_parser(formatter_class=argparse.RawTextHelpFormatter)
    parser.set_defaults(handler=None, quote_output=True)

    modules = [sub.name for sub in pkgutil.iter_modules(_tbl.__path__) if not sub.name.startswith('_')]
    handlers = [getattr(__import__('_tbl.'+name, fromlist=[name]), name) for name in modules]

    descr = '\n'.join(sorted(f'{h.get_name().ljust(20)}{h.__doc__ or ""}' for h in handlers))
    subparsers = parser.add_subparsers(dest='command', help=argparse.SUPPRESS, title='Commands', description=descr)

    for h in sorted(handlers, key=lambda h: h.get_name()):
        parents = [parent]
        if h.parser:
            parents.insert(0, h.parser)
        sub = subparsers.add_parser(h.get_name(), parents=parents, description=h.__doc__, add_help=False)
        sub.set_defaults(handler=h)

    if _utils.stdin_is_tty():
        parser.print_help()
        return

    opts, extras = parser.parse_known_args()
    opts.extras = extras
    opts.parser = parser
    opts.handler = opts.handler or _Base
    opts.ors = opts.ors or opts.irs

    opts.trailer = opts.trailer or 'always'
    opts.colour = os.environ.get('NO_COLOR', '') == '' and resolve_auto_colour(opts.colour or 'always')
    opts.numbered_columns = resolve_auto_colour(opts.numbered_columns or 'always')
    opts.rainbow_columns = opts.colour and resolve_auto_colour(opts.rainbow_columns or 'always')

    handler = opts.handler(opts)
    try:
        list(handler.process_file(sys.stdin.buffer))
    finally:
        if handler.outfile_proc:
            handler.outfile_proc.stdin.close()
            handler.outfile_proc.wait()

if __name__ == '__main__':
    try:
        main()
    except BrokenPipeError:
        pass
